// Per-domain project DTO type modules, re-exported from this barrel so existing
// `./types/project.ts` (and the top-level `types.ts`) import paths stay stable.
export type {
	ProjectFeatureDto,
	WebFeatureStats,
	WebFeatureStatusEntryDto,
	WebFeatureStatusType,
	WebFeatureSummaryDto,
} from './project/features.ts';
export type {
	ProjectActiveRunSummaryDto,
	ProjectDiscoverySkippedRootDto,
	ProjectImportActionDto,
	ProjectImportCandidateDto,
	ProjectImportCandidateResultDto,
	ProjectImportCandidateSignalDto,
	ProjectImportCandidatesResponseDto,
	ProjectInitFailureDto,
	ProjectImportResultDto,
	ProjectIntakeGitSummaryDto,
	ProjectIntakePreviewDto,
	ProjectNameSummaryDto,
	ProjectNamesResponseDto,
	ProjectSummaryDto,
	ProjectSummaryMetadataDto,
	ProjectsListResponseDto,
} from './project/listing.ts';
export type {
	AnsweredInterviewQuestionDto,
	FinalCheckStatus,
	FinalCheckSummary,
	GitCommitRefDto,
	ProjectArtifactCheckCounts,
	ProjectArtifactCheckSummary,
	ProjectArtifactFreshness,
	ProjectArtifactRecord,
	ProjectArtifactSeverity,
	ProjectInterviewDetailDto,
	ProjectInterviewProgress,
	ProjectInterviewQuestionDto,
	ProjectLocalIterationDto,
	ProjectLocalRunDto,
	ProjectMetadataDto,
	ProjectMilestoneSummary,
	ProjectPorts,
	ProjectRoadmapSummary,
	ProjectSyncState,
	ProjectSyncStateDto,
	ProjectUsageExecutionTargetDto,
	ProjectUsageModeDto,
	ProjectUsageSummaryDto,
	ProjectUsageTotalsDto,
} from './project/metadata.ts';
export type {
	ProjectCreateInputDto,
	ProjectCreateMode,
	ProjectCreateResultDto,
	ProjectCreateSpecInputDto,
	ProjectDetailDto,
	ProjectImplementationFeatureDto,
	ProjectImplementationStateDto,
	ProjectProfileUpdateDto,
	ProjectRecommendInputDto,
	ProjectRecommendMode,
	ProjectRecommendResultDto,
	ProjectStartImplementationResultDto,
} from './project/mutations.ts';
