/**
 * Reading the built container image: running a shell inside it, and turning its dpkg database into
 * the committed base-package inventory.
 *
 * Extracted from scripts/check-image-licenses.ts (max-lines split). Only `runInImage` exits, and
 * only for the two states that make every later question unanswerable: no docker on PATH, and a
 * `docker run` that failed. Everything else returns its answer to the gate.
 */
import { exit } from 'node:process';

export async function runInImage(image: string, script: string): Promise<string> {
	// No env spread: Bun.spawn inherits the environment, and check:env-spread forbids handing a
	// child the whole of process.env.
	let proc;
	try {
		proc = Bun.spawn(['docker', 'run', '--rm', '--entrypoint', 'sh', image, '-c', script], {
			stderr: 'pipe',
			stdout: 'pipe',
		});
	} catch {
		// Bun.spawn throws ENOENT for a missing binary rather than returning a non-zero exit, so a
		// machine without docker would otherwise die on an unhandled rejection and a stack trace.
		console.error('[FAIL] docker is not on PATH; cannot inspect the image.');
		console.error('Install Docker, or run this on a machine that has it.');
		exit(1);
	}
	const stdout = await new Response(proc.stdout).text();
	if ((await proc.exited) !== 0) {
		const stderr = await new Response(proc.stderr).text();
		console.error(`[FAIL] docker run failed against ${image}:`);
		console.error(stderr.trim() || stdout.trim());
		exit(1);
	}
	return stdout;
}

/**
 * Base-system packages and the licenses their copyright files declare.
 *
 * Debian has no license field in the package database (unlike apk), so the licenses come from
 * the DEP-5 `License:` lines in /usr/share/doc/<pkg>/copyright — which is also where each
 * package's own copyright notices live, and those ship in the image already.
 */
export async function collectBasePackages(image: string): Promise<string[]> {
	// Single quotes around the dpkg format string: sh would otherwise expand ${Package} itself
	// (to nothing) before dpkg-query ever saw it, and the inventory would come back empty.
	//
	// Licenses come from two places, because only some Debian copyright files are DEP-5:
	//   1. `License:` lines (machine-readable ones);
	//   2. references to /usr/share/common-licenses/<NAME> in the free-form ones.
	// Reading only (1) marked 18 packages UNKNOWN — including libc6 (LGPL-2.1) and the GCC runtime
	// (GPL-3 with the runtime exception), which are exactly the copyleft ones that matter.
	//
	// The SOURCE package name and version are what a corresponding-source request is actually
	// fulfilled from: a recipient needs `glibc`, not `libc6`.
	const script = [
		"for pkg in $(dpkg-query -W -f='${Package}\\n' 2>/dev/null); do",
		'  ver=$(dpkg-query -W -f=\'${Version}\' "$pkg" 2>/dev/null)',
		'  src=$(dpkg-query -W -f=\'${source:Package}\' "$pkg" 2>/dev/null)',
		'  srcver=$(dpkg-query -W -f=\'${source:Version}\' "$pkg" 2>/dev/null)',
		'  copyright="/usr/share/doc/$pkg/copyright"',
		'  declared=$(grep -hoiE "^License: [A-Za-z0-9.+-]+" "$copyright" 2>/dev/null | sed "s/^[Ll]icense: //")',
		'  referenced=$(grep -hoE "common-licenses/[A-Za-z0-9.+-]+" "$copyright" 2>/dev/null | sed "s|common-licenses/||")',
		'  lic=$(printf "%s\\n%s\\n" "$declared" "$referenced" | grep -v "^$" | sort -u | paste -sd "," -)',
		'  echo "$pkg|$ver|${src:-$pkg}|${srcver:-$ver}|${lic:-UNKNOWN}"',
		'done',
	].join('\n');

	const output = await runInImage(image, script);
	return output
		.split('\n')
		.map((line) => line.trim())
		.filter((line) => line.includes('|'))
		.sort();
}

export function renderInventory(packages: string[]): string {
	const copyleft = packages.filter((entry) => /GPL/i.test(entry.split('|')[4] ?? ''));
	const unknown = packages.filter((entry) => (entry.split('|')[4] ?? '') === 'UNKNOWN');

	return [
		'# Base image packages',
		'',
		"Operating-system packages in the aidd container image, read from the image's own dpkg",
		"database and the `License:` lines of each package's copyright file. Generated by",
		'`bun run licenses:image`; do not edit by hand.',
		'',
		`The image is built on a Debian (bookworm-slim) base and carries **${packages.length}** packages.`,
		'They are unmodified components of the base operating system, distributed alongside the',
		"application rather than linked into it. Each package's copyright file ships in the image at",
		'`/usr/share/doc/<package>/copyright`, and the license texts they reference ship at',
		'`/usr/share/common-licenses/`.',
		'',
		'## Copyleft packages',
		'',
		`**${copyleft.length}** of the ${packages.length} packages carry a GPL-family license. The`,
		'corresponding-source offer in [`SOURCE-OFFER.md`](./SOURCE-OFFER.md) covers them, and this is',
		'the list it points at. Fulfilment is answered from the SOURCE package, not the binary one (a',
		'request about `libc6` is served from `glibc`), so both are recorded. Debian publishes the',
		'sources at <https://sources.debian.org>.',
		'',
		...copyleft.map((entry) => {
			const [name, version, source, sourceVersion, license] = entry.split('|');
			return `- \`${name}@${version}\` (${license}) — source \`${source}@${sourceVersion}\``;
		}),
		'',
		...(unknown.length > 0
			? [
					'## Packages with no machine-readable license',
					'',
					`${unknown.length} package(s) declare no license this tool can read — neither a \`License:\``,
					'line nor a reference to `/usr/share/common-licenses/`. Their copyright files ship in the',
					'image at `/usr/share/doc/<package>/copyright` and must be read by hand rather than',
					'assumed permissive.',
					'',
					...unknown.map((entry) => {
						const [name, version] = entry.split('|');
						return `- \`${name}@${version}\``;
					}),
					'',
				]
			: []),
		'## All base image packages',
		'',
		'| Package | Version | Source package | Source version | Licenses |',
		'| ------- | ------- | -------------- | -------------- | -------- |',
		...packages.map((entry) => {
			const [name, version, source, sourceVersion, license] = entry.split('|');
			return `| ${name} | ${version} | ${source} | ${sourceVersion} | ${license || 'UNKNOWN'} |`;
		}),
		'',
	].join('\n');
}
