export const NOTICES_INTRO = `
This is the attribution appendix to [\`THIRD-PARTY-LICENSES.md\`](./THIRD-PARTY-LICENSES.md).

The summary document says which licenses are involved. This one reproduces, for every package
in the **runtime closure** (the direct production dependencies and everything they pull in
transitively), the license text and any \`NOTICE\` file that the package itself ships.

aidd ships as source, so it does not redistribute these packages: \`bun install\` resolves them
from npm on the user's machine. This appendix is therefore a courtesy record of what aidd builds
against rather than the discharge of a redistribution obligation. The obligations that do bind
aidd are the ones attached to material vendored into the repository, reproduced in the
non-package section below.

Generated by \`bun run licenses:generate\`; do not edit by hand.
`;

export const INTRO = `
aidd is distributed under the
[Functional Source License 1.1 (ALv2 future license)](./LICENSE)
(\`FSL-1.1-ALv2\`). FSL is a Fair Source license, not an open-source license: each
version converts to Apache-2.0 two years after its release. The third-party
dependencies below keep their own licenses regardless; FSL does not override them.

aidd is distributed as source — a git clone, or the source archive GitHub generates for each
release tag. Nothing in the npm graph travels with it, so the tables below inventory what aidd
builds against rather than what it redistributes. Material vendored directly into the repository
is the exception, and the notices it requires are carried by this document,
[\`THIRD-PARTY-NOTICES.md\`](./THIRD-PARTY-NOTICES.md), and [\`licenses/\`](./licenses).

The npm tables enumerate the *direct* production dependencies and summarize the rest of the npm
graph by license family. The non-package section is generated from
[\`licenses/distributed-materials.json\`](./licenses/distributed-materials.json), which classifies
the repository material distributed outside the npm graph.
`;

export const GROUPS = [
	{
		title: 'Backend and CLI runtime dependencies',
		workspaces: ['.', 'backend', 'cli', 'shared'],
	},
	{ title: 'Frontend runtime dependencies', workspaces: ['frontend'] },
];

export function scopeSections() {
	return [
		{
			body: `
Scope limits of the tables above, recorded rather than left implicit:

- **Transitive npm packages are not enumerated.** The tables list direct production
  dependencies only; the remainder of the graph appears as license-family counts.
- **Repository-distributed material is registry-backed.** Catalog files, public documents, and
  public static assets outside the npm graph are classified by exact path in
  \`licenses/distributed-materials.json\`. New or missing paths fail \`check:licenses\`.
- **Build and development tooling is not inventoried.** The counts above cover the packages aidd
  resolves at runtime, read from the manifests and the lockfile.

Per-package copyright lines, license text and \`NOTICE\` files for the whole runtime closure are
reproduced in [\`THIRD-PARTY-NOTICES.md\`](./THIRD-PARTY-NOTICES.md), which ships alongside this
file.
`,
			heading: 'Scope and known gaps',
		},
	];
}
