export const NOTICES_INTRO = `
This is the attribution appendix to [\`THIRD-PARTY-LICENSES.md\`](./THIRD-PARTY-LICENSES.md).

The summary document says which licenses are involved. This one reproduces, for every package
in the **runtime closure** (the direct production dependencies and everything they pull in
transitively, which is what the compiled binaries actually bundle), the license text and any
\`NOTICE\` file that the package itself ships. That is what MIT, BSD, ISC, Apache-2.0 and OFL
each require a redistributor to pass on: not the name of the license, but the package's own
copyright line and terms.

Generated by \`bun run licenses:generate\`; do not edit by hand.
`;

export const INTRO = `
aidd is distributed under the
[Functional Source License 1.1 (ALv2 future license)](./LICENSE)
(\`FSL-1.1-ALv2\`). FSL is a Fair Source license, not an open-source license: each
version converts to Apache-2.0 two years after its release. The third-party
dependencies below keep their own licenses regardless; FSL does not override them.

This document inventories the npm dependencies declared by this repository, and carries the
notice, source offer, and relink instructions for the Bun runtime that the standalone
binaries embed (see "Bundled runtime: Bun and its LGPL components" below). Required license texts
and legal-code links are carried by this document, [\`THIRD-PARTY-NOTICES.md\`](./THIRD-PARTY-NOTICES.md),
and [\`licenses/\`](./licenses), which ship with each release alongside [\`LICENSE\`](./LICENSE).

The npm tables enumerate the *direct* production dependencies and summarize the rest of the npm
graph by license family. The non-package section is generated from
[\`licenses/distributed-materials.json\`](./licenses/distributed-materials.json), which classifies
the repository material distributed outside the npm graph.
`;

export const GROUPS = [
	{
		title: 'Backend and CLI runtime dependencies',
		workspaces: ['.', 'backend', 'cli', 'shared'],
	},
	{ title: 'Frontend runtime dependencies', workspaces: ['frontend'] },
];

export function scopeSections(bunVersion: string) {
	return [
		{
			body: `
The standalone executables are built with \`bun build --compile\`
(\`scripts/lib/standalone/compile.ts\`), which embeds a copy of the **Bun ${bunVersion}**
runtime alongside the application code. Every binary aidd distributes therefore
redistributes Bun, and Bun statically links libraries under the LGPL. This section is the
notice that redistribution requires. Bun's own license text is reproduced in
[\`licenses/BUN-LICENSE.md\`](./licenses/BUN-LICENSE.md), and the binding corresponding-source and
relink offer is in [\`licenses/SOURCE-OFFER.md\`](./licenses/SOURCE-OFFER.md). Both ship with every
release. Static linking is the case the LGPL is most specific about — a recipient must be able to
modify the LGPL library and relink the program — so that offer, rather than a link to an upstream
repository, is what carries the obligation.

**LGPL components linked into the executable**

| Component | License | Full text |
| --------- | ------- | --------- |
| JavaScriptCore / WebKit (including WebCore files) | LGPL-2 | [\`licenses/LGPL-2.0.txt\`](./licenses/LGPL-2.0.txt) |
| TinyCC | LGPL-2.1 | [\`licenses/LGPL-2.1.txt\`](./licenses/LGPL-2.1.txt) |

Bun statically links many other libraries under permissive terms (BoringSSL, brotli,
libarchive, mimalloc, simdutf, c-ares, libicu, zlib-ng and others); they are listed
with their licenses in \`licenses/BUN-LICENSE.md\`. One of those linked libraries carries a
license *choice* rather than a single permissive license and is therefore called out
separately: zstd is dual-licensed BSD OR GPLv2; aidd selects the BSD branch, under which Bun
distributes it, so no GPL obligation attaches.

**Where to get the source**

- The patched WebKit/JavaScriptCore that Bun links is published at
  <https://github.com/oven-sh/webkit>.
- Bun itself (MIT) is at <https://github.com/oven-sh/bun>, tagged \`bun-v${bunVersion}\`.
- TinyCC is at <https://github.com/tinycc/tinycc>.

**How to modify the LGPL library and relink**

LGPL requires that a recipient be able to replace the LGPL library with a modified version
and relink the program. aidd's own source is available under FSL-1.1-ALv2, so the whole
executable can be rebuilt against a Bun you have modified:

1. Build a modified Bun following <https://github.com/oven-sh/bun/blob/main/LICENSE.md>:
   \`git submodule update --init --recursive\`, \`make jsc\`, \`zig build\`. This compiles
   JavaScriptCore and Bun's JSC bindings and produces a new \`bun\` binary with your changes.
2. Rebuild the aidd executable with that Bun: \`bun run build:standalone\`, which invokes
   \`bun build --compile\`. The resulting binary carries your modified JavaScriptCore.

Applying LGPL to the linked library does not place aidd's own application code under the
LGPL: LGPL exists precisely to permit non-LGPL programs to link against it. aidd's code
remains under FSL-1.1-ALv2.
`,
			heading: 'Bundled runtime: Bun and its LGPL components',
		},
		{
			body: `
Scope limits of the tables above, recorded rather than left implicit:

- **Transitive npm packages are not enumerated.** The tables list direct production
  dependencies only; the remainder of the graph appears as license-family counts. Compiled
  binaries bundle transitive runtime code too, and its attribution notices are not reproduced
  here.
- **Repository-distributed material is registry-backed.** Catalog files, public documents, and
  public static assets outside the npm graph are classified by exact path in
  \`licenses/distributed-materials.json\`. New or missing paths fail \`check:licenses\`.
- **Build and development tooling is not inventoried.** It is not distributed. The counts above
  cover the packages that ship, resolved from the manifests and the lockfile.

Per-package copyright lines, license text and \`NOTICE\` files for the whole runtime closure are
reproduced in [\`THIRD-PARTY-NOTICES.md\`](./THIRD-PARTY-NOTICES.md), which ships alongside this
file. That appendix, not this summary, is what carries the attribution obligations.
`,
			heading: 'Scope and known gaps',
		},
	];
}
