#!/usr/bin/env bun
import { spawnSync } from 'node:child_process';
/**
 * Bootstrap a locally-hosted production Docker deployment (spernakit's
 * deploy-local-prod.ts methodology, reduced to aidd's needs: the only secret
 * is web.authToken — there is no JWT/encryption-key factory, and migrations
 * run inside the binary at boot).
 *
 * Pre-authors the deploy tree so the container's first-boot bootstrap path is
 * skipped entirely:
 *   ${APPDATA_ROOT}/aidd/home/.aidd/config.json   (token pre-generated)
 *   ${APPDATA_ROOT}/aidd/{data,logs}
 *   ${APPDATA_ROOT}/aidd/docker-compose.yml + compose.vars
 *
 * Usage:
 *   bun scripts/deploy-docker.ts [options]
 *
 * Options:
 *   --appdata-root <path>   Host path for persistent volumes
 *                           (default Windows: D:/appdata/production, Linux: /opt/appdata)
 *   --projects-root <path>  Host path of project working trees mounted at /projects.
 *                           Must stay path-stable: /projects/... paths persist in the web DB.
 *   --port <n>              Host loopback port for the panel (default: 3210)
 *   --rotate-token          Regenerate web.authToken even if config exists (DESTRUCTIVE)
 *   --skip-image-check      Don't verify the image exists in the registry
 *   --up                    Run `docker compose pull && up -d` after scaffolding
 */
import { randomBytes } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parseArgs } from 'node:util';

const projectRoot = resolve(import.meta.dirname, '..');
const APP_SLUG = 'aidd';

/** Forward-slash form so the value works in compose files on both host OSes. */
function composePath(path: string): string {
	return path.replaceAll('\\', '/');
}

function fail(message: string): never {
	console.error(`[deploy-docker] ${message}`);
	process.exit(1);
}

const { values } = parseArgs({
	options: {
		'appdata-root': { type: 'string' },
		port: { default: '3210', type: 'string' },
		'projects-root': { type: 'string' },
		'rotate-token': { default: false, type: 'boolean' },
		'skip-image-check': { default: false, type: 'boolean' },
		up: { default: false, type: 'boolean' },
	},
});

const port = Number(values.port);
if (!Number.isInteger(port) || port < 1 || port > 65535) {
	fail('--port must be an integer between 1 and 65535');
}

const isWindows = process.platform === 'win32';
const appdataRoot = composePath(
	values['appdata-root'] ?? (isWindows ? 'D:/appdata/production' : '/opt/appdata'),
);
const projectsRoot = values['projects-root'] ? composePath(values['projects-root']) : null;
if (!projectsRoot) {
	fail('--projects-root is required (host path of the project trees aidd manages)');
}

const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8')) as {
	version: string;
};

const deployDir = join(appdataRoot, APP_SLUG);
const homeDir = join(deployDir, 'home');
const configDir = join(homeDir, '.aidd');
const configPath = join(configDir, 'config.json');
const composeSrc = join(projectRoot, 'docker-compose.production.yml');
const composeDest = join(deployDir, 'docker-compose.yml');
const composeVarsPath = join(deployDir, 'compose.vars');

if (!existsSync(composeSrc)) fail(`docker-compose.production.yml not found at ${composeSrc}`);

console.log(`Bootstrapping Docker deploy of ${APP_SLUG}@${pkg.version}`);
console.log(`  appdata:  ${deployDir}`);
console.log(`  projects: ${projectsRoot}`);
console.log(
	`  panel:    http://127.0.0.1:${port} (loopback; front with a TLS proxy for remote use)`,
);

if (!values['skip-image-check']) {
	const image = `ghcr.io/nomadicdaddy/${APP_SLUG}:${pkg.version}`;
	const inspect = spawnSync('docker', ['manifest', 'inspect', image], { stdio: 'pipe' });
	if (inspect.status !== 0) {
		fail(
			`${image} not found in the registry. Push it first ` +
				`(bun scripts/docker-image.ts push) or pass --skip-image-check.`,
		);
	}
	console.log('  image:    present in registry');
}

mkdirSync(configDir, { recursive: true });
mkdirSync(join(deployDir, 'data'), { recursive: true });
mkdirSync(join(deployDir, 'logs'), { recursive: true });
console.log('✓ Directory tree ready');
if (!isWindows) {
	console.log('  note: on Linux hosts the tree must be owned by uid 1000 (container user):');
	console.log(`        sudo chown -R 1000:1000 ${deployDir}`);
}

writeFileSync(
	composeVarsPath,
	[
		'# Generated by scripts/deploy-docker.ts — edit APP_VERSION to upgrade.',
		`APP_SLUG=${APP_SLUG}`,
		`APP_VERSION=${pkg.version}`,
		`APPDATA_ROOT=${appdataRoot}`,
		`PROJECTS_ROOT=${projectsRoot}`,
		`AIDD_PORT=${port}`,
		'AIDD_BACKUP_ON_START=1',
		'',
	].join('\n'),
);
console.log(`✓ Wrote ${composeVarsPath}`);

copyFileSync(composeSrc, composeDest);
console.log(`✓ Wrote ${composeDest}`);

if (existsSync(configPath) && !values['rotate-token']) {
	console.log(
		`✓ Config already exists at ${configPath} — leaving as-is (--rotate-token to regenerate)`,
	);
} else {
	if (existsSync(configPath)) {
		console.log(`⚠ --rotate-token: overwriting existing config at ${configPath}`);
	}
	const token = randomBytes(24).toString('hex');
	const config = {
		web: {
			allowedOrigins: [],
			allowedRoots: ['/projects'],
			allowRemote: true,
			authToken: token,
			hostname: '0.0.0.0',
			port: 3210,
		},
	};
	writeFileSync(configPath, `${JSON.stringify(config, null, '\t')}\n`, { mode: 0o600 });
	console.log(`✓ Wrote ${configPath}`);
	console.log(`  Web API auth token (store it now): ${token}`);
}

console.log('\nNext steps:');
console.log(`  cd ${deployDir}`);
console.log('  docker compose --env-file compose.vars pull');
console.log('  docker compose --env-file compose.vars up -d');
console.log(
	'  # provider keys: create compose.env next to the compose file (see compose.env.example)',
);

if (values.up) {
	console.log('\n--up: pulling and starting now...');
	for (const args of [
		['compose', '--env-file', 'compose.vars', 'pull'],
		['compose', '--env-file', 'compose.vars', 'up', '-d'],
	]) {
		const result = spawnSync('docker', args, { cwd: deployDir, stdio: 'inherit' });
		if (result.status !== 0) process.exit(result.status ?? 1);
	}
	console.log('✓ Container started. Tail logs with:');
	console.log(`  docker compose --env-file ${composeVarsPath} -f ${composeDest} logs -f`);
}
